SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[logFiles]
(
    [logFileId] [int] IDENTITY(1,1) NOT NULL,
    [transactionId] [int] NULL,
    [MachineId] [int] NULL,
    [FilePath] [varchar](255) NULL,
    PRIMARY KEY CLUSTERED 
(
	[logFileId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
